# Generated by Django 4.0.4 on 2023-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='number',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
