# Generated by Django 4.0.4 on 2023-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
