# Generated by Django 4.0.4 on 2023-01-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_datesubscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='faq',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
