"""
Django settings for django_site_track project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b3col@q^@xo!&l8foy=&60y9ly50l%s)6s$t^$6bff*4(fep)a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition
AUTH_USER_MODEL = 'site_track.MyUser'

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djstripe',
    'embed_video',
    'django_cleanup',
    'admin_reorder',
    'site_track_auth',
    'account',
    'site_track',
    'vehicle_ads',
    'auction',
    'stripe_sub',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_URL = '/static/'
# STATICFILES_DIRS = (os.path.join('static'), )
STATIC_ROOT = '/home/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_REDIRECT_URL = '/'

ROOT_URLCONF = 'django_site_track.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_site_track.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'site_track',
        'USER': 'postgres',
        'PASSWORD': 'example',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 60 * 60 * 7
SESSION_COOKIE_AGE_ADMIN = 60 * 60 * 48

ADMIN_REORDER = (
    {'app': 'site_track', 'models': (
         'site_track.MyUser',
    ), 'label': 'Users'},
    {'app': 'site_track', 'models': (
         'site_track.SaleAds',
    ), 'label': 'SaleAds'},
    {'app': 'site_track', 'models': (
        'site_track.CategoriesTrack',
        'site_track.ModelTrack',
        'site_track.MakeTrack',
        'site_track.TruckModel',
        'site_track.TruckMake',
        'site_track.ShouldInclude',
        'site_track.TypeOfTrailer',
        'site_track.SpringRide',
        'site_track.SpringRide',
    ), 'label': 'Marketplace Settings'},
    {'app': 'site_track', 'models': (
        'site_track.MuUser',
    ), 'label': 'Users'},
    {'app': 'site_track', 'models': (
        'site_track.SettingsFooter',
        'site_track.SettingsHeaderHome',
        'site_track.SettingsAuthBase',
        'site_track.SettingsHeaderInventoryGrid',
        'site_track.SettingsHeaderContact',
        'site_track.SettingsHeaderInventoryCatalog',
        'site_track.SettingsHeaderInventorySingle',
        'site_track.SettingsHeaderAboutUs',
        'site_track.SettingsHeaderPrivacy',
        'site_track.SettingsIndexHome',
    ), 'label': 'Global Pages Settings'},

    {'app': 'order', 'models': (
        'order.BillingInfo',
        'shop.Category',
        'cart.Cart',
        'cart.CartsProducts',
        'shop.DiscountCode',
        'order.Invoice',
        'shipping.ShippingInfo',
        'order.OrdersProducts',
        'order.OrdersAccessories',
    ), 'label': 'Website'},
    {'app': 'core', 'models': (
        'core.Faq',
    ), 'label': 'Faq'},
    'sites',
)


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.zoho.com"
EMAIL_HOST_USER = "site_track@zohomail.com"
EMAIL_HOST_PASSWORD = "Andrew-1994"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = "stahjrpower@yahoo.com"
CELERY_SEND_MAIL_HOST = 'https://buymyfleet.net/'


STRIPE_PRICE_ID_12_MONTHS = 'price_1Lg4T6K6rkKpcwrpjgWa7nCX'

STRIPE_LIVE_PUBLIC_KEY = os.environ.get("STRIPE_LIVE_PUBLIC_KEY", 'pk_test_51Lg4MyK6rkKpcwrpM9imgTsK4IupHl9BSeuzPgUQRWExpYnqHxr3Xe9juCUXGR10JXsiknlxoUeZGpTTw2lGG1UF00K0cn1Xv4')
STRIPE_LIVE_SECRET_KEY = os.environ.get("STRIPE_LIVE_SECRET_KEY", 'STRIPE_LIVE_SECRET_KEY = os.environ.get("STRIPE_LIVE_SECRET_KEY')
STRIPE_TEST_PUBLIC_KEY = os.environ.get("STRIPE_TEST_PUBLIC_KEY", 'pk_test_51Lg4MyK6rkKpcwrpM9imgTsK4IupHl9BSeuzPgUQRWExpYnqHxr3Xe9juCUXGR10JXsiknlxoUeZGpTTw2lGG1UF00K0cn1Xv4')
STRIPE_TEST_SECRET_KEY = os.environ.get("STRIPE_TEST_SECRET_KEY", 'sk_test_51Lg4MyK6rkKpcwrpBVyS7DCMIIiJxhxDwpCH5ufEg3MPS8QnZtcp3amLtQR5n5lQ1JKO4OVciqPL1K7kJguJZNUS005MqWi0jt')
STRIPE_LIVE_MODE = False
DJSTRIPE_WEBHOOK_SECRET = "whsec_QE3hbunXD3fpyvtkc1S1AORm39FzKbEp"
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"


try:
    from .local_settings import *
except ImportError:
    pass