# Generated by Django 4.0.4 on 2022-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
