# Generated by Django 4.0.4 on 2022-08-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maketrack',
            options={'verbose_name_plural': 'trailers make'},
        ),
        migrations.AlterModelOptions(
            name='modeltrack',
            options={'verbose_name_plural': 'trailers model'},
        ),
    ]
