# Generated by Django 4.0.4 on 2022-06-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0002_myuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
