# Generated by Django 4.0.4 on 2023-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0002_alter_maketrack_options_alter_modeltrack_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='email_1',
            field=models.EmailField(default='info@bymyfleet.net', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='email_2',
            field=models.EmailField(default='info@bymyfleet.net', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsindexhome',
            name='brand_part_title',
            field=models.TextField(default='browse by make'),
        ),
    ]
