# Generated by Django 4.0.4 on 2022-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0002_alter_myuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='sales',
            field=models.BooleanField(default=False),
        ),
    ]
