# Generated by Django 4.0.4 on 2022-08-26 16:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0003_saleads_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='last_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='sale_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 16, 0, 54, 317970, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='saleads',
            name='user_bet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleads',
            name='user_watch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
