# Generated by Django 4.0.4 on 2023-01-19 15:07

from django.db import migrations, models
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0003_remove_myuser_full_name_alter_settingsfooter_email_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsHeaderTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='Terms conditions')),
                ('inventory_link_name', models.TextField(default='Terms')),
            ],
            bases=(models.Model, site_track.models.IsNotSingleHeaderMixin),
        ),
    ]
