# Generated by Django 4.0.4 on 2022-06-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0003_myuser_code_myuser_is_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='code',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
