# Generated by Django 4.0.4 on 2022-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0004_alter_myuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reset_password_code',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
