# Generated by Django 4.0.4 on 2022-06-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0005_myuser_reset_password_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about_vendor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='account_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='facebook',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='instagram',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='pinterest',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='twitter',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='web_site',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='whatsapp',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='youtube',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zip',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
