# Generated by Django 4.0.4 on 2022-08-27 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0005_alter_saleads_sale_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleads',
            name='user_watch',
        ),
        migrations.AddField(
            model_name='saleads',
            name='user_watch',
            field=models.ManyToManyField(null=True, related_name='auction_watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
