# Generated by Django 4.0.4 on 2023-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0005_sizeoftrailer_saleads_size_of_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='roof_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='trailer_lining',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
