# Generated by Django 4.0.4 on 2022-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0006_myuser_about_vendor_myuser_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(choices=[('individual', 'individual'), ('dealership', 'dealership')], default='individual', max_length=120, null=True),
        ),
    ]
