# Generated by Django 4.0.4 on 2023-01-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0006_saleads_roof_type_saleads_trailer_lining'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpringRide',
            new_name='Suspension',
        ),
        migrations.RenameField(
            model_name='saleads',
            old_name='spring_ride',
            new_name='suspension',
        ),
    ]
