# Generated by Django 4.0.4 on 2022-08-27 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0006_remove_saleads_user_watch_saleads_user_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleads',
            name='user_bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bet', to=settings.AUTH_USER_MODEL),
        ),
    ]
