# Generated by Django 4.0.4 on 2022-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0007_alter_saleads_user_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='send_email_to_winner',
            field=models.BooleanField(default=False),
        ),
    ]
