# Generated by Django 4.0.4 on 2022-06-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0007_alter_myuser_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('vehicle_registration_number', models.CharField(max_length=120)),
                ('vehicle_registration_plate', models.CharField(max_length=120)),
                ('date_of_issue', models.DateField()),
                ('date_of_expire', models.DateField()),
                ('vehicle_type', models.CharField(max_length=60)),
                ('vehicle_make', models.CharField(max_length=60)),
                ('vehicle_fuel', models.CharField(max_length=60)),
                ('vehicle_colour', models.CharField(max_length=60)),
                ('vehicle_millage', models.CharField(max_length=60)),
                ('vehicle_price_amount', models.BigIntegerField(default=1000)),
                ('vehicle_price_type', models.CharField(max_length=60)),
                ('vehicle_condition', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('post_code', models.CharField(max_length=120)),
                ('ward_no', models.CharField(max_length=120)),
                ('road_no', models.CharField(max_length=120)),
                ('shop_no', models.CharField(max_length=120)),
                ('others', models.TextField(max_length=500)),
                ('sale_ads', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_address', to='site_track.saleads')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhotoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to='images/')),
                ('video_url', models.CharField(max_length=1024)),
                ('facebook', models.CharField(max_length=60, null=True)),
                ('instagram', models.CharField(max_length=60, null=True)),
                ('twitter', models.CharField(max_length=60, null=True)),
                ('youtube', models.CharField(max_length=60, null=True)),
                ('whatsapp', models.CharField(max_length=60, null=True)),
                ('pinterest', models.CharField(max_length=60, null=True)),
                ('sale_ads', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_photo_video', to='site_track.saleads')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_steering', models.BooleanField(default=False)),
                ('trunk_light', models.BooleanField(default=False)),
                ('sensing_lock', models.BooleanField(default=False)),
                ('rain_sensing', models.BooleanField(default=False)),
                ('vanity_mirror', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('alarm_system', models.BooleanField(default=False)),
                ('cd_player', models.BooleanField(default=False)),
                ('am_fm_radio', models.BooleanField(default=False)),
                ('driver_air_bag', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('panoramic_roof', models.BooleanField(default=False)),
                ('integrated_phone', models.BooleanField(default=False)),
                ('cylinders', models.BooleanField(default=False)),
                ('sale_ads', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_features', to='site_track.saleads')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_in_gallery', to='site_track.vehiclephotovideo')),
            ],
        ),
    ]
