# Generated by Django 4.0.4 on 2022-08-29 13:00

from django.db import migrations, models
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0008_saleads_send_email_to_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='faq')),
                ('inventory_link_name', models.TextField(default='Faq')),
            ],
            bases=(models.Model, site_track.models.IsNotSingleHeaderMixin),
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='email_1',
            field=models.EmailField(default='info@bymyfleet.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='email_2',
            field=models.EmailField(default='info@bymyfleet.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settingsheaderhome',
            name='header_text',
            field=models.CharField(default='An Online Auction for your used Trucks and Trailers', max_length=500, null=True),
        ),
    ]
