# Generated by Django 4.0.4 on 2023-01-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0008_saleads_height_saleads_hours_if_applicable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShouldInclude',
            new_name='TypeOfTruck',
        ),
        migrations.RenameField(
            model_name='saleads',
            old_name='should_include',
            new_name='type_of_truck',
        ),
    ]
