# Generated by Django 4.0.4 on 2022-06-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0008_saleads_vendoraddress_vehiclephotovideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='sale_created',
            field=models.BooleanField(default=True),
        ),
    ]
