# Generated by Django 4.0.4 on 2022-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0009_saleads_sale_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='vehicle_year',
            field=models.DateField(null=True),
        ),
    ]
