# Generated by Django 4.0.4 on 2022-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0009_faqheader_alter_settingsfooter_email_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address_of_company',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='number_of_trucks_in_fleet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='position_in_company',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='telephone_number_direct',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='phone_number_1',
            field=models.CharField(default='(260) 888-2323', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='phone_number_2',
            field=models.CharField(default='(260) 888-2323', max_length=120, null=True),
        ),
    ]
