# Generated by Django 4.0.4 on 2023-01-20 08:38

from django.db import migrations, models
import django.db.models.deletion
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0009_rename_shouldinclude_typeoftruck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='Horsepower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='SleeperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.ChoicesMixin),
        ),
        migrations.AddField(
            model_name='saleads',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.engine'),
        ),
        migrations.AddField(
            model_name='saleads',
            name='horse_power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.horsepower'),
        ),
        migrations.AddField(
            model_name='saleads',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.transmission'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='sleeper_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.sleepersize'),
        ),
    ]
