# Generated by Django 4.0.4 on 2022-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0010_saleads_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraddress',
            name='email',
            field=models.EmailField(default='fdfdf@mail.ua', max_length=254),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='phone_number',
            field=models.CharField(default='+3809568422', max_length=30),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='web_site',
            field=models.CharField(default='https://pypi.org/', max_length=120),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='others',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='road_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='ward_no',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
