# Generated by Django 4.0.4 on 2022-08-30 14:34

from django.db import migrations, models
import django.db.models.deletion
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0010_myuser_address_of_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShouldInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.CounterStrMixin, site_track.models.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='SpringRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.CounterStrMixin, site_track.models.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='TypeOfTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.CounterStrMixin, site_track.models.ChoicesMixin),
        ),
        migrations.AddField(
            model_name='saleads',
            name='air_ride',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='capacity_of_trailer',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='length',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='virgin_tires_or_recapped',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='width',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='should_include',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.shouldinclude'),
        ),
        migrations.AddField(
            model_name='saleads',
            name='spring_ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.springride'),
        ),
        migrations.AddField(
            model_name='saleads',
            name='type_of_5_trailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.typeoftrailer'),
        ),
    ]
