# Generated by Django 4.0.4 on 2022-08-30 15:57

from django.db import migrations, models
import django.db.models.deletion
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0011_shouldinclude_springride_typeoftrailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.CounterStrMixin, site_track.models.ChoicesMixin),
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            bases=(models.Model, site_track.models.CounterStrMixin, site_track.models.ChoicesMixin),
        ),
        migrations.AddField(
            model_name='saleads',
            name='truck_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.truckmake'),
        ),
        migrations.AddField(
            model_name='saleads',
            name='truck_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.truckmodel'),
        ),
    ]
