# Generated by Django 4.0.4 on 2023-01-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0011_remove_saleads_sleeper_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='sleeper_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.sleepersize'),
        ),
    ]
