# Generated by Django 4.0.4 on 2022-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0011_vendoraddress_email_vendoraddress_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephotovideo',
            name='linkedin',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
