# Generated by Django 4.0.4 on 2022-08-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0012_truckmake_truckmodel_saleads_truck_make_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='subscription',
            new_name='subscription_one_time',
        ),
    ]
