# Generated by Django 4.0.4 on 2023-01-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0012_saleads_sleeper_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleads',
            old_name='sleeper_size',
            new_name='sleeper_size_new',
        ),
    ]
