# Generated by Django 4.0.4 on 2022-08-30 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0013_rename_subscription_myuser_subscription_one_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleads',
            name='sale_end_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
