# Generated by Django 4.0.4 on 2022-06-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0013_remove_vehiclephotovideo_sale_ads_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleads',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageInGallery',
        ),
        migrations.DeleteModel(
            name='SaleAds',
        ),
    ]
