# Generated by Django 4.0.4 on 2022-08-30 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0015_alter_myuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about_vendor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='account_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address_of_company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pinterest',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='position_in_company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='subscribe_until_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='web_site',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='youtube',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='air_ride',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='any_know_problems_with_vehicle',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='capacity_of_trailer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='check_engine_warning_lights',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='jake_brake',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='number_of_aluminum_wheels',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='should_include',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.shouldinclude'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='sleeper_size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='spring_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.springride'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='tire_size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='truck_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.truckmake'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='truck_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.truckmodel'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='type_of_5_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.typeoftrailer'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='type_of_5_wheel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='user_bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='user_watch',
            field=models.ManyToManyField(blank=True, null=True, related_name='auction_watch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.categoriestrack'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_condition',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_fuel',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.maketrack'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_mileage',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_ads', to='site_track.modeltrack'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='virgin_tires_or_recapped',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='wheel_base',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
    ]
