# Generated by Django 4.0.4 on 2022-06-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0015_saleads_imageingallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleads',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='saleads',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
