# Generated by Django 4.0.4 on 2022-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0016_remove_saleads_whatsapp_alter_saleads_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleads',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='date_of_expire',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='post_code',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='shop_no',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='state',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_colour',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_condition',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_fuel',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_make',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_millage',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_price_amount',
            field=models.BigIntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_price_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_registration_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_registration_plate',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='video_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='web_site',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
