# Generated by Django 4.0.4 on 2022-08-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0016_alter_myuser_about_vendor_alter_myuser_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='zip',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
