# Generated by Django 4.0.4 on 2023-01-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0017_sleepersize_alter_categoriestrack_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='fuel_tank_size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='interior_trim_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='number_of_beds',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='size_of_body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
