# Generated by Django 4.0.4 on 2022-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0017_alter_saleads_city_alter_saleads_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleads',
            old_name='vehicle_millage',
            new_name='vehicle_transmission',
        ),
        migrations.AddField(
            model_name='saleads',
            name='vehicle_mileage',
            field=models.BigIntegerField(default=10000, null=True),
        ),
    ]
