# Generated by Django 4.0.4 on 2022-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0018_rename_vehicle_millage_saleads_vehicle_transmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_transmission',
            field=models.CharField(default='Manual', max_length=60),
        ),
    ]
