# Generated by Django 4.0.4 on 2022-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0019_alter_saleads_vehicle_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
