# Generated by Django 4.0.4 on 2022-06-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0020_saleads_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='vehicle_wheel',
            field=models.CharField(default='Left', max_length=60),
        ),
        migrations.AddField(
            model_name='saleads',
            name='vehicle_wheel_drive',
            field=models.CharField(default='Rear-Drive', max_length=60),
        ),
    ]
