# Generated by Django 4.0.4 on 2022-06-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0021_saleads_vehicle_wheel_saleads_vehicle_wheel_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subscribe_until_date',
            field=models.DateField(null=True),
        ),
    ]
