# Generated by Django 4.0.4 on 2022-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0022_myuser_country_myuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_about_company_title', models.TextField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt ullam repellat sit. Ipsa saepe maiores placeat eligendi totam quisquam necessitatibus dignissimos', null=True)),
                ('footer_about_company_text', models.TextField(default='About Company', null=True)),
                ('footer_facebook_url', models.URLField(default='https://www.facebook.com/', null=True)),
                ('footer_twitter_url', models.URLField(default='https://twitter.com/', null=True)),
                ('footer_linkedin_url', models.URLField(default='https://www.linkedin.com/', null=True)),
                ('footer_viber_phone', models.CharField(default='', max_length=60, null=True)),
                ('footer_youtube_url', models.URLField(default='https://www.youtube.com/', null=True)),
                ('email_1', models.EmailField(default='info@example.com', max_length=254, null=True)),
                ('email_2', models.EmailField(default='carrer@example.com', max_length=254, null=True)),
                ('phone_number_1', models.CharField(default='+91 987-654-3210', max_length=120, null=True)),
                ('phone_number_2', models.CharField(default='+91 987-654-5466', max_length=120, null=True)),
                ('address_top', models.CharField(default='1Hd- 50, 010 Avenue', max_length=120, null=True)),
                ('address_bottom', models.CharField(default='NY 90001 United States', max_length=120, null=True)),
                ('news_letter_title', models.CharField(default='Our Newsletter', max_length=120, null=True)),
                ('news_letter_text', models.CharField(default='Be the first to know about our offers and discounts by subscribing to the newsletter', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsHeaderHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='Used Equipment or Sale', max_length=120, null=True)),
                ('header_text', models.CharField(default='Browse through thousands of affordable alternatives to new equipment. View our detailed inspection reports and buy with confidence', max_length=500, null=True)),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254, null=True)),
                ('contact_number', models.CharField(default='+91 987-654-3210', max_length=120, null=True)),
            ],
        ),
    ]
