# Generated by Django 4.0.4 on 2022-06-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0023_settingsfooter_settingsheaderhome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_about_company_text',
            new_name='about_company_text',
        ),
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_about_company_title',
            new_name='about_company_title',
        ),
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_facebook_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_linkedin_url',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_twitter_url',
            new_name='twitter_url',
        ),
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_viber_phone',
            new_name='viber_phone',
        ),
        migrations.RenameField(
            model_name='settingsfooter',
            old_name='footer_youtube_url',
            new_name='youtube_url',
        ),
    ]
