# Generated by Django 4.0.4 on 2022-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0025_rename_viber_phone_settingsfooter_whatsapp_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='categories_images/')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='about_company_text',
            field=models.TextField(default='Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt ullam repellat sit. Ipsa saepe maiores placeat eligendi totam quisquam necessitatibus dignissimos', null=True),
        ),
        migrations.AlterField(
            model_name='settingsfooter',
            name='about_company_title',
            field=models.TextField(default='About Company', null=True),
        ),
    ]
