# Generated by Django 4.0.4 on 2022-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0027_alter_categoriestrack_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesTrackTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
