# Generated by Django 4.0.4 on 2022-06-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0028_categoriestracktest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriesTrackTest',
        ),
    ]
