# Generated by Django 4.0.4 on 2022-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0029_delete_categoriestracktest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsIndexHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_top_categories_title', models.TextField(default='find top categories')),
                ('find_top_categories_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing')),
                ('our_features_listing_title', models.TextField(default='our featured listing')),
                ('our_features_listing_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('brand_part_title', models.TextField(default='browse by top brands')),
                ('brand_part_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('price_part_title', models.TextField(default='our ads pricing plans')),
                ('price_part_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('recent_part_title', models.TextField(default='recent add vehiclesn')),
                ('reent_part_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
            ],
        ),
    ]
