# Generated by Django 4.0.4 on 2022-06-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0031_alter_saleads_vehicle_make_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleads',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='youtube',
        ),
    ]
