# Generated by Django 4.0.4 on 2022-06-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0034_rename_our_features_listing_text_settingsindexhome_part_features_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsindexhome',
            old_name='part_text_text',
            new_name='part_start_text',
        ),
    ]
