# Generated by Django 4.0.4 on 2022-06-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0035_rename_part_text_text_settingsindexhome_part_start_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsindexhome',
            old_name='reent_part_text',
            new_name='recent_part_text',
        ),
    ]
