# Generated by Django 4.0.4 on 2022-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0036_rename_reent_part_text_settingsindexhome_recent_part_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriestrack',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
