# Generated by Django 4.0.4 on 2022-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0037_alter_categoriestrack_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsHeaderInventoryGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='Inventory Grid View')),
                ('inventory_link_name', models.TextField(default='Inventory Grid')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsHeaderInventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='Inventory List View')),
                ('inventory_link_name', models.TextField(default='Inventory List')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsHeaderInventorySingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='Inventory Single Page')),
                ('inventory_link_name', models.TextField(default='Inventory List')),
                ('inventory_single_page', models.TextField(default='Inventory Single')),
            ],
        ),
    ]
