# Generated by Django 4.0.4 on 2022-06-23 08:50

from django.db import migrations, models
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0039_settingsheaderinventorycatalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsHeaderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='contact us')),
                ('inventory_link_name', models.TextField(default='Contact')),
            ],
            bases=(models.Model, site_track.models.IsNotSingleHeaderMixin),
        ),
        migrations.AlterModelOptions(
            name='saleads',
            options={'ordering': ('-created_at',)},
        ),
    ]
