# Generated by Django 4.0.4 on 2022-06-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0040_settingsheadercontact_alter_saleads_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleads',
            old_name='vehicle_type',
            new_name='vehicle_category',
        ),
    ]
