# Generated by Django 4.0.4 on 2022-06-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0041_rename_vehicle_type_saleads_vehicle_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleads',
            old_name='vehicle_make',
            new_name='vehicle_model',
        ),
    ]
