# Generated by Django 4.0.4 on 2022-06-23 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0042_rename_vehicle_make_saleads_vehicle_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleads',
            old_name='city',
            new_name='sleeper_size',
        ),
        migrations.RenameField(
            model_name='saleads',
            old_name='country',
            new_name='tire_size',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='alarm_system',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='am_fm_radio',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='cd_player',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='cruise_control',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='cylinders',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='date_of_expire',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='driver_air_bag',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='integrated_phone',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='others',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='panoramic_roof',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='power_steering',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='rain_sensing',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='road_no',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='sale_created',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='sensing_lock',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='shop_no',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='state',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='trunk_light',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vanity_mirror',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_colour',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_mileage',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_price_type',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_registration_number',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_registration_plate',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_transmission',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_wheel',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='vehicle_wheel_drive',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='ward_no',
        ),
        migrations.RemoveField(
            model_name='saleads',
            name='web_site',
        ),
        migrations.AddField(
            model_name='saleads',
            name='any_know_problems_with_vehicle',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='check_engine_warning_lights',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='jake_brake',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='number_of_aluminum_wheels',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='tire_percent_front_left',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='saleads',
            name='tire_percent_front_right',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='saleads',
            name='tire_percent_rear_drive_tires',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='saleads',
            name='tire_percent_rear_left',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='saleads',
            name='tire_percent_rear_right',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='saleads',
            name='type_of_5_wheel',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='saleads',
            name='wheel_base',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='saleads',
            name='vehicle_price_amount',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
    ]
