# Generated by Django 4.0.4 on 2022-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0043_rename_city_saleads_sleeper_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleads',
            name='vehicle_mileage',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
    ]
