# Generated by Django 4.0.4 on 2022-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0044_saleads_vehicle_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeReviewIndexHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sale', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('review_title', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('review_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('review_author', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('review_author_red_text', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicin')),
                ('image', models.ImageField(null=True, upload_to='settings_images/')),
            ],
        ),
    ]
