# Generated by Django 4.0.4 on 2022-06-25 10:45

from django.db import migrations, models
import site_track.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0045_fakereviewindexhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsHeaderInventoryAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='About our company')),
                ('inventory_link_name', models.TextField(default='About-Us')),
            ],
            bases=(models.Model, site_track.models.IsNotSingleHeaderMixin),
        ),
        migrations.CreateModel(
            name='SettingsHeaderInventoryPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_title', models.TextField(default='Privacy Policy')),
                ('inventory_link_name', models.TextField(default='Privacy')),
            ],
            bases=(models.Model, site_track.models.IsNotSingleHeaderMixin),
        ),
    ]
