# Generated by Django 4.0.4 on 2022-06-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_track', '0046_settingsheaderinventoryaboutus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingsHeaderInventoryAboutUs',
            new_name='SettingsHeaderAboutUs',
        ),
        migrations.RenameModel(
            old_name='SettingsHeaderInventoryPrivacy',
            new_name='SettingsHeaderPrivacy',
        ),
    ]
